// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_social_api.Data;

#nullable disable

namespace dotnet_social_api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240826102254_InnitSeedingevenmore")]
    partial class InnitSeedingevenmore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8d50e43e-1012-46c6-a587-6593bb7aa450",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "bb10387d-4b67-40ab-88dd-a72e98011353",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("dotnet_social_api.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Great post! Really enjoyed the insights.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 1,
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Thanks for sharing this information.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 2,
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 3,
                            Body = "This was very helpful. Looking forward to more updates!",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 3,
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 4,
                            Body = "I disagree with some of the points mentioned.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 4,
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Can you provide more details on this topic?",
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 5,
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Amazing content! Keep up the great work.",
                            CreatedOn = new DateTime(2024, 8, 20, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 6,
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Very informative, but could use some examples.",
                            CreatedOn = new DateTime(2024, 8, 19, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 7,
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Nice article. I learned something new today!",
                            CreatedOn = new DateTime(2024, 8, 18, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 8,
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 9,
                            Body = "Good read, but could be more concise.",
                            CreatedOn = new DateTime(2024, 8, 17, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 9,
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Interesting perspective, thanks for sharing!",
                            CreatedOn = new DateTime(2024, 8, 16, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 10,
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        });
                });

            modelBuilder.Entity("dotnet_social_api.Models.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolloweeUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolloweeUserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FollowerUserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeUserProfileId");

                    b.HasIndex("FollowerUserProfileId");

                    b.ToTable("Follows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FolloweeUserId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6",
                            FollowerUserId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 2,
                            FolloweeUserId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb",
                            FollowerUserId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 3,
                            FolloweeUserId = "0f6a348a-760e-4f67-8a72-fb1397b43f23",
                            FollowerUserId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 4,
                            FolloweeUserId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b",
                            FollowerUserId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 5,
                            FolloweeUserId = "ed677356-50e3-4640-8077-99db7f391a5b",
                            FollowerUserId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 6,
                            FolloweeUserId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6",
                            FollowerUserId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 7,
                            FolloweeUserId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb",
                            FollowerUserId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 8,
                            FolloweeUserId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b",
                            FollowerUserId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 9,
                            FolloweeUserId = "ed677356-50e3-4640-8077-99db7f391a5b",
                            FollowerUserId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 10,
                            FolloweeUserId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6",
                            FollowerUserId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        });
                });

            modelBuilder.Entity("dotnet_social_api.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 1,
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 2,
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 3,
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 4,
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            PostId = 5,
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 6,
                            CommentId = 1,
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 7,
                            CommentId = 2,
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 8,
                            CommentId = 3,
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 9,
                            CommentId = 4,
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 10,
                            CommentId = 5,
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        });
                });

            modelBuilder.Entity("dotnet_social_api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MessageThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToUserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromUserProfileId");

                    b.HasIndex("MessageThreadId");

                    b.HasIndex("ToUserProfileId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("dotnet_social_api.Models.MessageThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MessageThreads");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromUserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToUserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromUserProfileId");

                    b.HasIndex("ToUserProfileId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserProfileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Welcome to the system! Excited to have you here.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 2,
                            Body = "System maintenance scheduled for tonight.",
                            CreatedOn = new DateTime(2024, 8, 26, 4, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 3,
                            Body = "New feature release notes available in the documentation.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 4,
                            Body = "Reminder: Update your profile settings.",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 5,
                            Body = "Check out the latest system reports.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "ed677356-50e3-4640-8077-99db7f391a5b"
                        },
                        new
                        {
                            Id = 6,
                            Body = "Just pushed a new update to the repository.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 7,
                            Body = "Working on improving the API performance.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 8,
                            Body = "Dev meetup scheduled for next week.",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 9,
                            Body = "New blog post on best coding practices.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 10,
                            Body = "Exploring new tools for developers.",
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6"
                        },
                        new
                        {
                            Id = 11,
                            Body = "Check out the latest design trends.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 12,
                            Body = "Redesigned the homepage for a client.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 13,
                            Body = "Design tips for creating effective UI.",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 14,
                            Body = "How to use color theory in design.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 15,
                            Body = "Design project management tips.",
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb"
                        },
                        new
                        {
                            Id = 16,
                            Body = "New marketing strategy launched.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 17,
                            Body = "Top 5 tips for effective social media marketing.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 18,
                            Body = "Exploring new digital marketing tools.",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 19,
                            Body = "Analyzing the latest marketing trends.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 20,
                            Body = "Effective strategies for increasing engagement.",
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "0f6a348a-760e-4f67-8a72-fb1397b43f23"
                        },
                        new
                        {
                            Id = 21,
                            Body = "Support hours extended this week.",
                            CreatedOn = new DateTime(2024, 8, 25, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 22,
                            Body = "New troubleshooting guide available.",
                            CreatedOn = new DateTime(2024, 8, 24, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 23,
                            Body = "How to resolve common support issues.",
                            CreatedOn = new DateTime(2024, 8, 23, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 24,
                            Body = "Tips for better customer support.",
                            CreatedOn = new DateTime(2024, 8, 22, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        },
                        new
                        {
                            Id = 25,
                            Body = "New features in the support portal.",
                            CreatedOn = new DateTime(2024, 8, 21, 10, 22, 54, 139, DateTimeKind.Utc).AddTicks(4220),
                            UserProfileId = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b"
                        });
                });

            modelBuilder.Entity("dotnet_social_api.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ed677356-50e3-4640-8077-99db7f391a5b",
                            AccessFailedCount = 0,
                            Bio = "System Administrator",
                            ConcurrencyStamp = "9a75cd59-5f41-461c-b4ea-f8ec78327687",
                            DateJoined = new DateTime(2024, 8, 26, 12, 22, 54, 142, DateTimeKind.Local).AddTicks(8810),
                            Email = "admin@localhost",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDO/JrW4tyojy8Fu4PvAofbJ5eGSgDx4YrTeFgKmRUebZ7m8qMmVdxfx1udJeH64oQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4fb2b885-84c1-4871-95e3-50c7cc5c15e8",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Website = "http://localhost"
                        },
                        new
                        {
                            Id = "b31adf09-b1f4-4f2d-bb02-6d1e9f7c65b6",
                            AccessFailedCount = 0,
                            Bio = "Software Developer",
                            ConcurrencyStamp = "6a572f87-15cd-4b7b-aa10-2651be8ce6ab",
                            DateJoined = new DateTime(2024, 8, 26, 12, 22, 54, 210, DateTimeKind.Local).AddTicks(5620),
                            Email = "devuser@localhost",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "DEVUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEI+CoQ4NoHiCitfSmzHmZ4KfW3uMD7V+C1+tyCHX6u0ZBY81sH+Eb3MGXiBoXUdDHw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8d48e441-7a7f-4f9b-b747-ad0221c05acf",
                            TwoFactorEnabled = false,
                            UserName = "DevUser",
                            Website = "http://devsite.local"
                        },
                        new
                        {
                            Id = "4d1cf4a5-4e5d-43d5-bb1d-22a5b0c85dcb",
                            AccessFailedCount = 0,
                            Bio = "Creative Designer",
                            ConcurrencyStamp = "12873df2-fd34-4db5-a13c-d173c7835a94",
                            DateJoined = new DateTime(2024, 8, 26, 12, 22, 54, 278, DateTimeKind.Local).AddTicks(1100),
                            Email = "designguru@localhost",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "DESIGNGURU",
                            PasswordHash = "AQAAAAIAAYagAAAAEFaU6dRp/NERIl60rMLQG1oNX9DbfvbRVt6tdCGyqNAGL0qzf+DGs7NhRrwKYL3ZgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29c88977-344f-4db6-ab32-d02e6fbd01de",
                            TwoFactorEnabled = false,
                            UserName = "DesignGuru",
                            Website = "http://design.local"
                        },
                        new
                        {
                            Id = "0f6a348a-760e-4f67-8a72-fb1397b43f23",
                            AccessFailedCount = 0,
                            Bio = "Marketing Specialist",
                            ConcurrencyStamp = "de688614-3089-4c23-9cf6-381025b16348",
                            DateJoined = new DateTime(2024, 8, 26, 12, 22, 54, 345, DateTimeKind.Local).AddTicks(6850),
                            Email = "marketer@localhost",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MARKETER",
                            PasswordHash = "AQAAAAIAAYagAAAAEG59js6gntlZsgGuno/LFxdBrW75CPRfkXonMj1L2qzf0BEEOnsnVHxBeaYI512t0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b691d229-5a82-43e7-ba80-11b3dc4c0cfe",
                            TwoFactorEnabled = false,
                            UserName = "Marketer",
                            Website = "http://market.local"
                        },
                        new
                        {
                            Id = "a87b2e1e-39a4-4fd1-8237-f013f4e9cf6b",
                            AccessFailedCount = 0,
                            Bio = "Customer Support Tech",
                            ConcurrencyStamp = "876b9785-a84a-4f98-a1f9-7ae60d24a01d",
                            DateJoined = new DateTime(2024, 8, 26, 12, 22, 54, 413, DateTimeKind.Local).AddTicks(2650),
                            Email = "supporttech@localhost",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPPORTTECH",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxtvKPO47TBToRsaqQZWjNttfZoHEzaq0AtHxrb3+td1zYQLimM702eo78EXDi/lQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb0ef431-1727-4349-acec-a3b59de94248",
                            TwoFactorEnabled = false,
                            UserName = "SupportTech",
                            Website = "http://support.local"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_social_api.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_social_api.Models.Comment", b =>
                {
                    b.HasOne("dotnet_social_api.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("dotnet_social_api.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Follow", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", "FolloweeUserProfile")
                        .WithMany()
                        .HasForeignKey("FolloweeUserProfileId");

                    b.HasOne("dotnet_social_api.Models.UserProfile", "FollowerUserProfile")
                        .WithMany()
                        .HasForeignKey("FollowerUserProfileId");

                    b.Navigation("FolloweeUserProfile");

                    b.Navigation("FollowerUserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Like", b =>
                {
                    b.HasOne("dotnet_social_api.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("dotnet_social_api.Models.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId");

                    b.HasOne("dotnet_social_api.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Message", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", "FromUserProfile")
                        .WithMany()
                        .HasForeignKey("FromUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_social_api.Models.MessageThread", "MessageThread")
                        .WithMany("Messages")
                        .HasForeignKey("MessageThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_social_api.Models.UserProfile", "ToUserProfile")
                        .WithMany()
                        .HasForeignKey("ToUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUserProfile");

                    b.Navigation("MessageThread");

                    b.Navigation("ToUserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Notification", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", "FromUserProfile")
                        .WithMany()
                        .HasForeignKey("FromUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_social_api.Models.UserProfile", "ToUserProfile")
                        .WithMany()
                        .HasForeignKey("ToUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUserProfile");

                    b.Navigation("ToUserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.Post", b =>
                {
                    b.HasOne("dotnet_social_api.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("dotnet_social_api.Models.MessageThread", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
